import {
  ApprovalLog,
  AttendanceCorrection,
  AttendanceLocation,
  AttendanceRecord,
  Branch,
  BusinessTripRequest,
  AppNotification,
  Company,
  Department,
  Employee,
  Holiday,
  LeaveBalance,
  LeaveRequest,
  LeaveType,
  OvertimeRequest,
  PermissionRequest,
  Position,
  Shift,
  WorkScheduleAssignment,
  EmployeeSalaryProfile,
  PayrollBatch,
  PayrollItem,
  ReimbursementClaim,
  PerformanceAppraisal,
  CompanyAnnouncement,
  EmployeeContractTracker,
} from '../types';

export const DEMO_COMPANY: Company = {
  id: 'comp-01',
  code: 'NPD',
  name: 'PT Nusantara Prima Digital',
  app_name: 'AT-HR Enterprise',
  tagline: 'Smart Solutions for Smart Business',
  app_short_name: 'AT-HR',
  brand_icon: 'gem',
  address: 'Sahid Sudirman Center Lt. 28, Jl. Jend. Sudirman Kav. 86, Jakarta Pusat',
  phone: '+62 21 5790 8820',
  email: 'corporate@nusantaraprima.co.id',
  website: 'https://nusantaraprima.co.id',
};

export const DEMO_BRANCHES: Branch[] = [
  {
    id: 'branch-jkt',
    company_id: 'comp-01',
    code: 'JKT-HQ',
    name: 'Jakarta Head Office',
    address: 'Sahid Sudirman Center Lt. 28, Sudirman CBD',
    city: 'Jakarta Pusat',
    latitude: -6.21462,
    longitude: 106.82155,
    radius_meters: 150,
    policy: 'BLOCK_OUTSIDE_RADIUS',
    is_active: true,
  },
  {
    id: 'branch-sby',
    company_id: 'comp-01',
    code: 'SBY-01',
    name: 'Surabaya Tech Hub',
    address: 'Intiland Tower Lt. 9, Jl. Panglima Sudirman',
    city: 'Surabaya',
    latitude: -7.27584,
    longitude: 112.75338,
    radius_meters: 100,
    policy: 'BLOCK_OUTSIDE_RADIUS',
    is_active: true,
  },
  {
    id: 'branch-bdg',
    company_id: 'comp-01',
    code: 'BDG-01',
    name: 'Bandung R&D Center',
    address: 'Dago Creative Park Block B-4, Jl. Ir. H. Juanda',
    city: 'Bandung',
    latitude: -6.88541,
    longitude: 107.61366,
    radius_meters: 120,
    policy: 'ALLOW_WITH_APPROVAL',
    is_active: true,
  },
];

export const DEMO_DEPARTMENTS: Department[] = [
  {
    id: 'dept-eng',
    company_id: 'comp-01',
    code: 'ENG',
    name: 'Engineering & Technology',
    description: 'Core platform engineering, infrastructure, and QA',
  },
  {
    id: 'dept-hr',
    company_id: 'comp-01',
    code: 'HCD',
    name: 'Human Resources & People',
    description: 'Talent management, people operations, and employee development',
  },
  {
    id: 'dept-fin',
    company_id: 'comp-01',
    code: 'FIN',
    name: 'Finance & Accounting',
    description: 'Financial management, compliance, and accounts',
  },
  {
    id: 'dept-prod',
    company_id: 'comp-01',
    code: 'PRD',
    name: 'Product & Design',
    description: 'Product lifecycle, UX research, and UI design',
  },
  {
    id: 'dept-sales',
    company_id: 'comp-01',
    code: 'SLS',
    name: 'Sales & Business Operations',
    description: 'Enterprise accounts, client relations, and growth',
  },
];

export const DEMO_POSITIONS: Position[] = [
  { id: 'pos-coo', department_id: 'dept-hr', code: 'COO', name: 'Chief Operations Officer', level: 5 },
  { id: 'pos-hrd', department_id: 'dept-hr', code: 'HR-DIR', name: 'Head of Human Resources', level: 4 },
  { id: 'pos-engm', department_id: 'dept-eng', code: 'ENG-MGR', name: 'Engineering Manager', level: 4 },
  { id: 'pos-finm', department_id: 'dept-fin', code: 'FIN-MGR', name: 'Finance Manager', level: 4 },
  { id: 'pos-sr-fe', department_id: 'dept-eng', code: 'SR-FE', name: 'Senior Frontend Engineer', level: 3 },
  { id: 'pos-sr-be', department_id: 'dept-eng', code: 'SR-BE', name: 'Senior Backend Engineer', level: 3 },
  { id: 'pos-devops', department_id: 'dept-eng', code: 'DEVOPS', name: 'DevOps & Cloud Engineer', level: 3 },
  { id: 'pos-hr-gen', department_id: 'dept-hr', code: 'HR-GEN', name: 'People Partner & HR Specialist', level: 2 },
  { id: 'pos-fin-acc', department_id: 'dept-fin', code: 'ACC', name: 'Senior Accounting Specialist', level: 2 },
  { id: 'pos-pm', department_id: 'dept-prod', code: 'PM', name: 'Product Manager', level: 3 },
  { id: 'pos-ux', department_id: 'dept-prod', code: 'UX-DES', name: 'Product Designer', level: 2 },
  { id: 'pos-ae', department_id: 'dept-sales', code: 'ACC-EXEC', name: 'Enterprise Account Executive', level: 2 },
];

export const DEMO_SHIFTS: Shift[] = [
  {
    id: 'shift-norm',
    company_id: 'comp-01',
    name: 'Normal Office Shift',
    shift_type: 'Normal',
    start_time: '08:00',
    end_time: '17:00',
    break_start: '12:00',
    break_end: '13:00',
    tolerance_minutes: 10,
    is_cross_day: false,
    is_active: true,
  },
  {
    id: 'shift-morn',
    company_id: 'comp-01',
    name: 'Morning Support Shift',
    shift_type: 'Morning',
    start_time: '06:00',
    end_time: '14:00',
    break_start: '10:00',
    break_end: '11:00',
    tolerance_minutes: 10,
    is_cross_day: false,
    is_active: true,
  },
  {
    id: 'shift-afternoon',
    company_id: 'comp-01',
    name: 'Afternoon Ops Shift',
    shift_type: 'Afternoon',
    start_time: '14:00',
    end_time: '22:00',
    break_start: '18:00',
    break_end: '19:00',
    tolerance_minutes: 10,
    is_cross_day: false,
    is_active: true,
  },
  {
    id: 'shift-night',
    company_id: 'comp-01',
    name: 'Night Cross-Day Shift',
    shift_type: 'CrossDay',
    start_time: '22:00',
    end_time: '06:00',
    break_start: '02:00',
    break_end: '03:00',
    tolerance_minutes: 15,
    is_cross_day: true,
    is_active: true,
  },
];

export const DEMO_ATTENDANCE_LOCATIONS: AttendanceLocation[] = [
  {
    id: 'loc-jkt',
    branch_id: 'branch-jkt',
    name: 'Jakarta Head Office - Sudirman',
    latitude: -6.21462,
    longitude: 106.82155,
    radius_meters: 150,
    policy: 'BLOCK_OUTSIDE_RADIUS',
    is_active: true,
  },
  {
    id: 'loc-sby',
    branch_id: 'branch-sby',
    name: 'Surabaya Tech Hub - Gubeng',
    latitude: -7.27584,
    longitude: 112.75338,
    radius_meters: 100,
    policy: 'BLOCK_OUTSIDE_RADIUS',
    is_active: true,
  },
  {
    id: 'loc-bdg',
    branch_id: 'branch-bdg',
    name: 'Bandung R&D Center - Dago',
    latitude: -6.88541,
    longitude: 107.61366,
    radius_meters: 120,
    policy: 'ALLOW_WITH_APPROVAL',
    is_active: true,
  },
];

export const DEMO_EMPLOYEES: Employee[] = [
  // 1. Super Admin
  {
    id: 'emp-01',
    employee_code: 'EMP-001',
    nik: '3171018809910001',
    full_name: 'Triyanto Andi',
    gender: 'Male',
    email: 'triyanto.andi@nusantaraprima.co.id',
    phone: '+62 811 9283 1001',
    role: 'SUPER_ADMIN',
    company_id: 'comp-01',
    branch_id: 'branch-jkt',
    department_id: 'dept-hr',
    position_id: 'pos-coo',
    employment_type: 'Permanent',
    employment_status: 'Active',
    join_date: '2021-01-15',
    branch_name: 'Jakarta Head Office',
    department_name: 'Human Resources & People',
    position_name: 'Chief Operations Officer',
  },
  // 2. HR Admin
  {
    id: 'emp-02',
    employee_code: 'EMP-002',
    nik: '3171029004920002',
    full_name: 'Siti Rahmawati',
    gender: 'Female',
    email: 'siti.rahmawati@nusantaraprima.co.id',
    phone: '+62 812 8829 4402',
    role: 'HR_ADMIN',
    company_id: 'comp-01',
    branch_id: 'branch-jkt',
    department_id: 'dept-hr',
    position_id: 'pos-hrd',
    employment_type: 'Permanent',
    employment_status: 'Active',
    join_date: '2021-03-01',
    branch_name: 'Jakarta Head Office',
    department_name: 'Human Resources & People',
    position_name: 'Head of Human Resources',
    manager_id: 'emp-01',
    manager_name: 'Triyanto Andi',
  },
  // 3. Manager 1 (Engineering)
  {
    id: 'emp-03',
    employee_code: 'EMP-003',
    nik: '3171038506890003',
    full_name: 'Budi Santoso',
    gender: 'Male',
    email: 'budi.santoso@nusantaraprima.co.id',
    phone: '+62 813 1192 5503',
    role: 'MANAGER',
    company_id: 'comp-01',
    branch_id: 'branch-jkt',
    department_id: 'dept-eng',
    position_id: 'pos-engm',
    employment_type: 'Permanent',
    employment_status: 'Active',
    join_date: '2021-05-10',
    branch_name: 'Jakarta Head Office',
    department_name: 'Engineering & Technology',
    position_name: 'Engineering Manager',
    manager_id: 'emp-01',
    manager_name: 'Triyanto Andi',
  },
  // 4. Manager 2 (Finance)
  {
    id: 'emp-04',
    employee_code: 'EMP-004',
    nik: '3171048811880004',
    full_name: 'Farhan Maulana',
    gender: 'Male',
    email: 'farhan.maulana@nusantaraprima.co.id',
    phone: '+62 811 4432 9904',
    role: 'MANAGER',
    company_id: 'comp-01',
    branch_id: 'branch-jkt',
    department_id: 'dept-fin',
    position_id: 'pos-finm',
    employment_type: 'Permanent',
    employment_status: 'Active',
    join_date: '2021-06-01',
    branch_name: 'Jakarta Head Office',
    department_name: 'Finance & Accounting',
    position_name: 'Finance Manager',
    manager_id: 'emp-01',
    manager_name: 'Triyanto Andi',
  },
  // 5. Manager 3 (Surabaya Tech Hub Lead)
  {
    id: 'emp-05',
    employee_code: 'EMP-005',
    nik: '3578058702900005',
    full_name: 'Rian Adiputra',
    gender: 'Male',
    email: 'rian.adiputra@nusantaraprima.co.id',
    phone: '+62 812 7744 1105',
    role: 'MANAGER',
    company_id: 'comp-01',
    branch_id: 'branch-sby',
    department_id: 'dept-eng',
    position_id: 'pos-engm',
    employment_type: 'Permanent',
    employment_status: 'Active',
    join_date: '2021-09-15',
    branch_name: 'Surabaya Tech Hub',
    department_name: 'Engineering & Technology',
    position_name: 'Engineering Manager (Hub Lead)',
    manager_id: 'emp-01',
    manager_name: 'Triyanto Andi',
  },
  // 6. Employee (Active demo user)
  {
    id: 'emp-06',
    employee_code: 'EMP-006',
    nik: '3171069408940006',
    full_name: 'Dewi Lestari',
    gender: 'Female',
    email: 'dewi.lestari@nusantaraprima.co.id',
    phone: '+62 813 5566 7706',
    role: 'EMPLOYEE',
    company_id: 'comp-01',
    branch_id: 'branch-jkt',
    department_id: 'dept-eng',
    position_id: 'pos-sr-fe',
    employment_type: 'Permanent',
    employment_status: 'Active',
    join_date: '2022-01-10',
    branch_name: 'Jakarta Head Office',
    department_name: 'Engineering & Technology',
    position_name: 'Senior Frontend Engineer',
    manager_id: 'emp-03',
    manager_name: 'Budi Santoso',
  },
  // 7. Employee (Backend)
  {
    id: 'emp-07',
    employee_code: 'EMP-007',
    nik: '3171079305930007',
    full_name: 'Ahmad Rizky',
    gender: 'Male',
    email: 'ahmad.rizky@nusantaraprima.co.id',
    phone: '+62 811 8899 3307',
    role: 'EMPLOYEE',
    company_id: 'comp-01',
    branch_id: 'branch-jkt',
    department_id: 'dept-eng',
    position_id: 'pos-sr-be',
    employment_type: 'Permanent',
    employment_status: 'Active',
    join_date: '2022-02-14',
    branch_name: 'Jakarta Head Office',
    department_name: 'Engineering & Technology',
    position_name: 'Senior Backend Engineer',
    manager_id: 'emp-03',
    manager_name: 'Budi Santoso',
  },
  // 8. Employee (DevOps)
  {
    id: 'emp-08',
    employee_code: 'EMP-008',
    nik: '3171089209920008',
    full_name: 'Dimas Wicaksono',
    gender: 'Male',
    email: 'dimas.w@nusantaraprima.co.id',
    phone: '+62 812 3344 5508',
    role: 'EMPLOYEE',
    company_id: 'comp-01',
    branch_id: 'branch-jkt',
    department_id: 'dept-eng',
    position_id: 'pos-devops',
    employment_type: 'Permanent',
    employment_status: 'Active',
    join_date: '2022-04-01',
    branch_name: 'Jakarta Head Office',
    department_name: 'Engineering & Technology',
    position_name: 'DevOps & Cloud Engineer',
    manager_id: 'emp-03',
    manager_name: 'Budi Santoso',
  },
  // 9. Employee (Product Designer)
  {
    id: 'emp-09',
    employee_code: 'EMP-009',
    nik: '3171099603960009',
    full_name: 'Jessica Tanuwijaya',
    gender: 'Female',
    email: 'jessica.t@nusantaraprima.co.id',
    phone: '+62 813 6677 8809',
    role: 'EMPLOYEE',
    company_id: 'comp-01',
    branch_id: 'branch-jkt',
    department_id: 'dept-prod',
    position_id: 'pos-ux',
    employment_type: 'Permanent',
    employment_status: 'Active',
    join_date: '2022-05-16',
    branch_name: 'Jakarta Head Office',
    department_name: 'Product & Design',
    position_name: 'Product Designer',
    manager_id: 'emp-03',
    manager_name: 'Budi Santoso',
  },
  // 10. Employee (HR Specialist)
  {
    id: 'emp-10',
    employee_code: 'EMP-010',
    nik: '3171109507950010',
    full_name: 'Nadia Putri',
    gender: 'Female',
    email: 'nadia.putri@nusantaraprima.co.id',
    phone: '+62 811 2233 4410',
    role: 'EMPLOYEE',
    company_id: 'comp-01',
    branch_id: 'branch-jkt',
    department_id: 'dept-hr',
    position_id: 'pos-hr-gen',
    employment_type: 'Contract',
    employment_status: 'Active',
    join_date: '2022-07-01',
    branch_name: 'Jakarta Head Office',
    department_name: 'Human Resources & People',
    position_name: 'People Partner & HR Specialist',
    manager_id: 'emp-02',
    manager_name: 'Siti Rahmawati',
  },
  // 11. Employee (Accounting)
  {
    id: 'emp-11',
    employee_code: 'EMP-011',
    nik: '3171119101910011',
    full_name: 'Hendra Gunawan',
    gender: 'Male',
    email: 'hendra.g@nusantaraprima.co.id',
    phone: '+62 812 9988 7711',
    role: 'EMPLOYEE',
    company_id: 'comp-01',
    branch_id: 'branch-jkt',
    department_id: 'dept-fin',
    position_id: 'pos-fin-acc',
    employment_type: 'Permanent',
    employment_status: 'Active',
    join_date: '2022-08-15',
    branch_name: 'Jakarta Head Office',
    department_name: 'Finance & Accounting',
    position_name: 'Senior Accounting Specialist',
    manager_id: 'emp-04',
    manager_name: 'Farhan Maulana',
  },
  // 12. Employee (Surabaya FE)
  {
    id: 'emp-12',
    employee_code: 'EMP-012',
    nik: '3578129509950012',
    full_name: 'Faisal Anugerah',
    gender: 'Male',
    email: 'faisal.a@nusantaraprima.co.id',
    phone: '+62 813 4455 6612',
    role: 'EMPLOYEE',
    company_id: 'comp-01',
    branch_id: 'branch-sby',
    department_id: 'dept-eng',
    position_id: 'pos-sr-fe',
    employment_type: 'Permanent',
    employment_status: 'Active',
    join_date: '2022-10-01',
    branch_name: 'Surabaya Tech Hub',
    department_name: 'Engineering & Technology',
    position_name: 'Senior Frontend Engineer',
    manager_id: 'emp-05',
    manager_name: 'Rian Adiputra',
  },
  // 13. Employee (Surabaya BE)
  {
    id: 'emp-13',
    employee_code: 'EMP-013',
    nik: '3578139612960013',
    full_name: 'Maya Kusuma',
    gender: 'Female',
    email: 'maya.k@nusantaraprima.co.id',
    phone: '+62 811 5566 7713',
    role: 'EMPLOYEE',
    company_id: 'comp-01',
    branch_id: 'branch-sby',
    department_id: 'dept-eng',
    position_id: 'pos-sr-be',
    employment_type: 'Contract',
    employment_status: 'Active',
    join_date: '2022-11-15',
    branch_name: 'Surabaya Tech Hub',
    department_name: 'Engineering & Technology',
    position_name: 'Senior Backend Engineer',
    manager_id: 'emp-05',
    manager_name: 'Rian Adiputra',
  },
  // 14. Employee (Bandung Mobile Engineer)
  {
    id: 'emp-14',
    employee_code: 'EMP-014',
    nik: '3273149404940014',
    full_name: 'Reza Pratama',
    gender: 'Male',
    email: 'reza.p@nusantaraprima.co.id',
    phone: '+62 812 6677 8814',
    role: 'EMPLOYEE',
    company_id: 'comp-01',
    branch_id: 'branch-bdg',
    department_id: 'dept-eng',
    position_id: 'pos-sr-fe',
    employment_type: 'Permanent',
    employment_status: 'Active',
    join_date: '2023-01-05',
    branch_name: 'Bandung R&D Center',
    department_name: 'Engineering & Technology',
    position_name: 'Mobile Engineer (Bandung Hub)',
    manager_id: 'emp-03',
    manager_name: 'Budi Santoso',
  },
  // 15. Employee (Bandung Designer)
  {
    id: 'emp-15',
    employee_code: 'EMP-015',
    nik: '3273159702970015',
    full_name: 'Clara Bella',
    gender: 'Female',
    email: 'clara.b@nusantaraprima.co.id',
    phone: '+62 813 7788 9915',
    role: 'EMPLOYEE',
    company_id: 'comp-01',
    branch_id: 'branch-bdg',
    department_id: 'dept-prod',
    position_id: 'pos-ux',
    employment_type: 'Probation',
    employment_status: 'Active',
    join_date: '2023-03-01',
    branch_name: 'Bandung R&D Center',
    department_name: 'Product & Design',
    position_name: 'UI/UX Visual Designer',
    manager_id: 'emp-03',
    manager_name: 'Budi Santoso',
  },
  // 16. Employee (Account Executive)
  {
    id: 'emp-16',
    employee_code: 'EMP-016',
    nik: '3171169308930016',
    full_name: 'Bambang Irawan',
    gender: 'Male',
    email: 'bambang.i@nusantaraprima.co.id',
    phone: '+62 811 1122 3316',
    role: 'EMPLOYEE',
    company_id: 'comp-01',
    branch_id: 'branch-jkt',
    department_id: 'dept-sales',
    position_id: 'pos-ae',
    employment_type: 'Permanent',
    employment_status: 'Active',
    join_date: '2023-04-10',
    branch_name: 'Jakarta Head Office',
    department_name: 'Sales & Business Operations',
    position_name: 'Enterprise Account Executive',
    manager_id: 'emp-01',
    manager_name: 'Triyanto Andi',
  },
  // 17. Employee (Internship FE)
  {
    id: 'emp-17',
    employee_code: 'EMP-017',
    nik: '3171170105010017',
    full_name: 'Kevin Jonathan',
    gender: 'Male',
    email: 'kevin.j@nusantaraprima.co.id',
    phone: '+62 812 2233 4417',
    role: 'EMPLOYEE',
    company_id: 'comp-01',
    branch_id: 'branch-jkt',
    department_id: 'dept-eng',
    position_id: 'pos-sr-fe',
    employment_type: 'Internship',
    employment_status: 'Active',
    join_date: '2023-07-01',
    branch_name: 'Jakarta Head Office',
    department_name: 'Engineering & Technology',
    position_name: 'Frontend Engineering Intern',
    manager_id: 'emp-03',
    manager_name: 'Budi Santoso',
  },
  // 18. Employee (Internship HR)
  {
    id: 'emp-18',
    employee_code: 'EMP-018',
    nik: '3171180206020018',
    full_name: 'Anisa Maharani',
    gender: 'Female',
    email: 'anisa.m@nusantaraprima.co.id',
    phone: '+62 813 3344 5518',
    role: 'EMPLOYEE',
    company_id: 'comp-01',
    branch_id: 'branch-jkt',
    department_id: 'dept-hr',
    position_id: 'pos-hr-gen',
    employment_type: 'Internship',
    employment_status: 'Active',
    join_date: '2023-08-01',
    branch_name: 'Jakarta Head Office',
    department_name: 'Human Resources & People',
    position_name: 'HR Operations Intern',
    manager_id: 'emp-02',
    manager_name: 'Siti Rahmawati',
  },
  // 19. Employee (Finance Analyst)
  {
    id: 'emp-19',
    employee_code: 'EMP-019',
    nik: '3171199510950019',
    full_name: 'Taufik Hidayat',
    gender: 'Male',
    email: 'taufik.h@nusantaraprima.co.id',
    phone: '+62 811 6677 8819',
    role: 'EMPLOYEE',
    company_id: 'comp-01',
    branch_id: 'branch-jkt',
    department_id: 'dept-fin',
    position_id: 'pos-fin-acc',
    employment_type: 'Permanent',
    employment_status: 'Active',
    join_date: '2023-09-01',
    branch_name: 'Jakarta Head Office',
    department_name: 'Finance & Accounting',
    position_name: 'Financial Planning Analyst',
    manager_id: 'emp-04',
    manager_name: 'Farhan Maulana',
  },
  // 20. Employee (Resigned)
  {
    id: 'emp-20',
    employee_code: 'EMP-020',
    nik: '3171209001900020',
    full_name: 'Daniel Christian',
    gender: 'Male',
    email: 'daniel.c@nusantaraprima.co.id',
    phone: '+62 812 8899 0020',
    role: 'EMPLOYEE',
    company_id: 'comp-01',
    branch_id: 'branch-jkt',
    department_id: 'dept-eng',
    position_id: 'pos-sr-be',
    employment_type: 'Permanent',
    employment_status: 'Resigned',
    join_date: '2021-04-01',
    resign_date: '2023-12-31',
    branch_name: 'Jakarta Head Office',
    department_name: 'Engineering & Technology',
    position_name: 'Backend Engineer (Alumni)',
    manager_id: 'emp-03',
    manager_name: 'Budi Santoso',
  },
];

// Helper to generate today's ISO date
const todayStr = new Date().toISOString().split('T')[0];

export const DEMO_ATTENDANCE: AttendanceRecord[] = [
  {
    id: 'att-01',
    employee_id: 'emp-01',
    attendance_date: todayStr,
    shift_id: 'shift-norm',
    clock_in_time: `${todayStr}T07:55:12Z`,
    clock_in_lat: -6.21461,
    clock_in_lng: 106.82153,
    clock_in_accuracy: 12,
    clock_in_distance_meters: 15,
    clock_in_location_name: 'Jakarta Head Office',
    clock_in_device: 'Chrome on macOS',
    clock_in_status: 'present',
    late_minutes: 0,
    early_checkout_minutes: 0,
    work_duration_minutes: 0,
    overtime_minutes: 0,
    is_outside_geofence: false,
    approval_status: 'APPROVED',
    employee_name: 'Triyanto Andi',
    employee_code: 'EMP-001',
    department_name: 'Human Resources & People',
    branch_name: 'Jakarta Head Office',
    shift_name: 'Normal Office Shift',
  },
  {
    id: 'att-02',
    employee_id: 'emp-02',
    attendance_date: todayStr,
    shift_id: 'shift-norm',
    clock_in_time: `${todayStr}T08:04:45Z`,
    clock_in_lat: -6.21463,
    clock_in_lng: 106.82156,
    clock_in_accuracy: 14,
    clock_in_distance_meters: 20,
    clock_in_location_name: 'Jakarta Head Office',
    clock_in_device: 'Safari on iOS Device',
    clock_in_status: 'present',
    late_minutes: 0,
    early_checkout_minutes: 0,
    work_duration_minutes: 0,
    overtime_minutes: 0,
    is_outside_geofence: false,
    approval_status: 'APPROVED',
    employee_name: 'Siti Rahmawati',
    employee_code: 'EMP-002',
    department_name: 'Human Resources & People',
    branch_name: 'Jakarta Head Office',
    shift_name: 'Normal Office Shift',
  },
  {
    id: 'att-03',
    employee_id: 'emp-03',
    attendance_date: todayStr,
    shift_id: 'shift-norm',
    clock_in_time: `${todayStr}T08:08:10Z`,
    clock_in_lat: -6.21460,
    clock_in_lng: 106.82158,
    clock_in_accuracy: 10,
    clock_in_distance_meters: 25,
    clock_in_location_name: 'Jakarta Head Office',
    clock_in_device: 'Chrome on Windows',
    clock_in_status: 'present', // within 10 min tolerance
    late_minutes: 0,
    early_checkout_minutes: 0,
    work_duration_minutes: 0,
    overtime_minutes: 0,
    is_outside_geofence: false,
    approval_status: 'APPROVED',
    employee_name: 'Budi Santoso',
    employee_code: 'EMP-003',
    department_name: 'Engineering & Technology',
    branch_name: 'Jakarta Head Office',
    shift_name: 'Normal Office Shift',
  },
  {
    id: 'att-04',
    employee_id: 'emp-07',
    attendance_date: todayStr,
    shift_id: 'shift-norm',
    clock_in_time: `${todayStr}T08:24:18Z`,
    clock_in_lat: -6.21465,
    clock_in_lng: 106.82154,
    clock_in_accuracy: 15,
    clock_in_distance_meters: 18,
    clock_in_location_name: 'Jakarta Head Office',
    clock_in_device: 'Chrome on Linux',
    clock_in_status: 'late',
    late_minutes: 24,
    early_checkout_minutes: 0,
    work_duration_minutes: 0,
    overtime_minutes: 0,
    is_outside_geofence: false,
    approval_status: 'APPROVED',
    notes: 'Traffic congestion on Sudirman',
    employee_name: 'Ahmad Rizky',
    employee_code: 'EMP-007',
    department_name: 'Engineering & Technology',
    branch_name: 'Jakarta Head Office',
    shift_name: 'Normal Office Shift',
  },
  {
    id: 'att-05',
    employee_id: 'emp-12',
    attendance_date: todayStr,
    shift_id: 'shift-morn',
    clock_in_time: `${todayStr}T05:58:30Z`,
    clock_in_lat: -7.27582,
    clock_in_lng: 112.75339,
    clock_in_accuracy: 8,
    clock_in_distance_meters: 12,
    clock_in_location_name: 'Surabaya Tech Hub',
    clock_in_device: 'Chrome on Windows',
    clock_in_status: 'present',
    late_minutes: 0,
    early_checkout_minutes: 0,
    work_duration_minutes: 0,
    overtime_minutes: 0,
    is_outside_geofence: false,
    approval_status: 'APPROVED',
    employee_name: 'Faisal Anugerah',
    employee_code: 'EMP-012',
    department_name: 'Engineering & Technology',
    branch_name: 'Surabaya Tech Hub',
    shift_name: 'Morning Support Shift',
  },
];

// ==========================================
// PHASE 2 SEED DATA: LEAVE, PERMISSION, OVERTIME
// ==========================================

export const DEMO_LEAVE_TYPES: LeaveType[] = [
  {
    id: 'lt-ann',
    code: 'ANNUAL',
    name: 'Annual Leave',
    default_days: 12,
    is_paid: true,
    description: 'Standard paid annual vacation leave entitlement',
  },
  {
    id: 'lt-sick',
    code: 'SICK',
    name: 'Sick Leave',
    default_days: 14,
    is_paid: true,
    description: 'Leave for illness with doctor certificate required for >1 day',
  },
  {
    id: 'lt-mar',
    code: 'MARRIAGE',
    name: 'Marriage Leave',
    default_days: 3,
    is_paid: true,
    description: 'Special leave for employee personal marriage',
  },
  {
    id: 'lt-mat',
    code: 'MATERNITY',
    name: 'Maternity Leave',
    default_days: 90,
    is_paid: true,
    description: 'Paid maternity leave for female employees (3 months)',
  },
  {
    id: 'lt-ber',
    code: 'BEREAVEMENT',
    name: 'Bereavement Leave',
    default_days: 2,
    is_paid: true,
    description: 'Leave for demise of immediate family member',
  },
  {
    id: 'lt-spec',
    code: 'SPECIAL',
    name: 'Special / Religious Leave',
    default_days: 2,
    is_paid: true,
    description: 'Special pilgrimage or religious rituals',
  },
];

export const DEMO_LEAVE_BALANCES: LeaveBalance[] = [
  // emp-06 (Dewi Lestari - Software Engineer)
  {
    id: 'bal-01',
    employee_id: 'emp-06',
    leave_type_id: 'lt-ann',
    year: 2026,
    entitlement: 12,
    used: 3,
    pending: 2,
    remaining: 7,
    leave_type_name: 'Annual Leave',
  },
  {
    id: 'bal-02',
    employee_id: 'emp-06',
    leave_type_id: 'lt-sick',
    year: 2026,
    entitlement: 14,
    used: 1,
    pending: 0,
    remaining: 13,
    leave_type_name: 'Sick Leave',
  },
  // emp-07 (Ahmad Rizky)
  {
    id: 'bal-03',
    employee_id: 'emp-07',
    leave_type_id: 'lt-ann',
    year: 2026,
    entitlement: 12,
    used: 4,
    pending: 0,
    remaining: 8,
    leave_type_name: 'Annual Leave',
  },
  // emp-08 (Dimas Wicaksono)
  {
    id: 'bal-04',
    employee_id: 'emp-08',
    leave_type_id: 'lt-ann',
    year: 2026,
    entitlement: 12,
    used: 2,
    pending: 3,
    remaining: 7,
    leave_type_name: 'Annual Leave',
  },
  // emp-03 (Budi Santoso - Manager)
  {
    id: 'bal-05',
    employee_id: 'emp-03',
    leave_type_id: 'lt-ann',
    year: 2026,
    entitlement: 15,
    used: 2,
    pending: 0,
    remaining: 13,
    leave_type_name: 'Annual Leave',
  },
];

export const DEMO_LEAVE_REQUESTS: LeaveRequest[] = [
  {
    id: 'lr-01',
    employee_id: 'emp-06',
    leave_type_id: 'lt-ann',
    start_date: '2026-10-08',
    end_date: '2026-10-09',
    total_days: 2,
    reason: 'Family gathering in Yogyakarta',
    status: 'PENDING',
    current_approver_id: 'emp-03', // Manager Budi Santoso
    created_at: '2026-09-28T09:15:00Z',
    employee_name: 'Dewi Lestari',
    employee_code: 'EMP-006',
    department_name: 'Engineering & Technology',
    branch_name: 'Jakarta Head Office',
    leave_type_name: 'Annual Leave',
  },
  {
    id: 'lr-02',
    employee_id: 'emp-08',
    leave_type_id: 'lt-ann',
    start_date: '2026-10-15',
    end_date: '2026-10-17',
    total_days: 3,
    reason: 'Personal time off for house moving',
    status: 'PENDING',
    current_approver_id: 'emp-03', // Manager Budi Santoso
    created_at: '2026-09-29T11:30:00Z',
    employee_name: 'Dimas Wicaksono',
    employee_code: 'EMP-008',
    department_name: 'Engineering & Technology',
    branch_name: 'Jakarta Head Office',
    leave_type_name: 'Annual Leave',
  },
  {
    id: 'lr-03',
    employee_id: 'emp-07',
    leave_type_id: 'lt-sick',
    start_date: '2026-09-18',
    end_date: '2026-09-18',
    total_days: 1,
    reason: 'Medical checkup and flu recovery',
    status: 'APPROVED',
    current_approver_id: 'emp-03',
    approver_name: 'Budi Santoso',
    approver_comment: 'Approved. Get well soon!',
    created_at: '2026-09-18T07:45:00Z',
    employee_name: 'Ahmad Rizky',
    employee_code: 'EMP-007',
    department_name: 'Engineering & Technology',
    branch_name: 'Jakarta Head Office',
    leave_type_name: 'Sick Leave',
  },
];

export const DEMO_PERMISSION_REQUESTS: PermissionRequest[] = [
  {
    id: 'pr-01',
    employee_id: 'emp-06',
    permission_date: '2026-10-02',
    start_time: '13:00',
    end_time: '15:30',
    permission_type: 'Medical',
    reason: 'Dentist appointment and crown check',
    notes: 'Will resume work online after 15:30',
    status: 'PENDING',
    current_approver_id: 'emp-03',
    created_at: '2026-09-29T14:20:00Z',
    employee_name: 'Dewi Lestari',
    employee_code: 'EMP-006',
    department_name: 'Engineering & Technology',
  },
  {
    id: 'pr-02',
    employee_id: 'emp-09',
    permission_date: '2026-09-25',
    start_time: '09:00',
    end_time: '11:00',
    permission_type: 'Emergency',
    reason: 'Electric meter repair emergency at residence',
    status: 'APPROVED',
    current_approver_id: 'emp-03',
    approver_name: 'Budi Santoso',
    approver_comment: 'Approved. Thanks for informing ahead.',
    created_at: '2026-09-24T16:00:00Z',
    employee_name: 'Jessica Tanuwijaya',
    employee_code: 'EMP-009',
    department_name: 'Product & Design',
  },
];

export const DEMO_OVERTIME_REQUESTS: OvertimeRequest[] = [
  {
    id: 'ot-01',
    employee_id: 'emp-06',
    overtime_date: '2026-10-01',
    start_time: '17:30',
    end_time: '20:30',
    duration_hours: 3.0,
    reason: 'Core payment gateway integration and unit testing prior to QA freeze',
    project_name: 'Fintech Core Migration v2',
    status: 'PENDING',
    current_approver_id: 'emp-03',
    created_at: '2026-09-29T16:00:00Z',
    employee_name: 'Dewi Lestari',
    employee_code: 'EMP-006',
    department_name: 'Engineering & Technology',
  },
  {
    id: 'ot-02',
    employee_id: 'emp-07',
    overtime_date: '2026-09-26',
    start_time: '18:00',
    end_time: '21:00',
    duration_hours: 3.0,
    reason: 'Database performance index tuning and load testing',
    project_name: 'PostgreSQL Cloud Migration',
    status: 'APPROVED',
    current_approver_id: 'emp-03',
    approver_name: 'Budi Santoso',
    approver_comment: 'Approved. Great job on the query optimizations.',
    created_at: '2026-09-25T15:30:00Z',
    employee_name: 'Ahmad Rizky',
    employee_code: 'EMP-007',
    department_name: 'Engineering & Technology',
  },
];

export const DEMO_APPROVAL_LOGS: ApprovalLog[] = [
  {
    id: 'al-01',
    request_type: 'LEAVE',
    request_id: 'lr-03',
    approver_id: 'emp-03',
    approver_name: 'Budi Santoso',
    approver_role: 'MANAGER',
    previous_status: 'PENDING',
    new_status: 'APPROVED',
    comment: 'Approved. Get well soon!',
    created_at: '2026-09-18T08:10:00Z',
  },
  {
    id: 'al-02',
    request_type: 'PERMISSION',
    request_id: 'pr-02',
    approver_id: 'emp-03',
    approver_name: 'Budi Santoso',
    approver_role: 'MANAGER',
    previous_status: 'PENDING',
    new_status: 'APPROVED',
    comment: 'Approved. Thanks for informing ahead.',
    created_at: '2026-09-24T16:45:00Z',
  },
];

// ==========================================
// PHASE 3 SEED DATA: HOLIDAYS & CORRECTIONS
// ==========================================

export const DEMO_HOLIDAYS: Holiday[] = [
  {
    id: 'hol-01',
    company_id: 'comp-01',
    name: "New Year's Day 2026",
    date: '2026-01-01',
    holiday_type: 'National',
    description: 'International New Year celebration',
  },
  {
    id: 'hol-02',
    company_id: 'comp-01',
    name: "Isra Mi'raj",
    date: '2026-01-16',
    holiday_type: 'National',
    description: 'Ascension of Prophet Muhammad SAW',
  },
  {
    id: 'hol-03',
    company_id: 'comp-01',
    name: 'Chinese New Year 2577',
    date: '2026-02-17',
    holiday_type: 'National',
    description: 'Tahun Baru Imlek 2577 Kongzili',
  },
  {
    id: 'hol-04',
    company_id: 'comp-01',
    name: 'Hari Suci Nyepi',
    date: '2026-03-20',
    holiday_type: 'National',
    description: 'Tahun Baru Saka 1948',
  },
  {
    id: 'hol-05',
    company_id: 'comp-01',
    name: 'Idul Fitri 1447 H (Day 1)',
    date: '2026-03-21',
    holiday_type: 'National',
    description: 'Hari Raya Idul Fitri 1447 Hijriah',
  },
  {
    id: 'hol-06',
    company_id: 'comp-01',
    name: 'Cuti Bersama Idul Fitri',
    date: '2026-03-23',
    holiday_type: 'Collective_Leave',
    description: 'Government collective leave for Eid Mubarak',
  },
  {
    id: 'hol-07',
    company_id: 'comp-01',
    name: 'International Labor Day',
    date: '2026-05-01',
    holiday_type: 'National',
    description: 'May Day Worker Commemoration',
  },
  {
    id: 'hol-08',
    company_id: 'comp-01',
    name: 'Independence Day of Indonesia',
    date: '2026-08-17',
    holiday_type: 'National',
    description: 'Hari Kemerdekaan Republik Indonesia ke-81',
  },
  {
    id: 'hol-09',
    company_id: 'comp-01',
    name: 'PT NPD Corporate Anniversary',
    date: '2026-11-15',
    holiday_type: 'Company',
    description: 'Corporate Founding Day & Employee Appreciation Holiday',
  },
];

export const DEMO_ATTENDANCE_CORRECTIONS: AttendanceCorrection[] = [
  {
    id: 'cor-01',
    employee_id: 'emp-06',
    attendance_date: '2026-09-29',
    correction_type: 'FORGOT_CLOCK_OUT',
    original_clock_in: '2026-09-29T08:02:15Z',
    original_clock_out: undefined,
    requested_clock_in: '08:02',
    requested_clock_out: '17:35',
    reason: 'Left desk immediately for urgent customer emergency support meeting and forgot to clock out on terminal.',
    status: 'PENDING',
    approver_id: 'emp-03',
    created_at: '2026-09-30T08:15:00Z',
    employee_name: 'Dewi Lestari',
    employee_code: 'EMP-006',
    department_name: 'Engineering & Technology',
    branch_name: 'Jakarta Head Office',
  },
];

export const DEMO_BUSINESS_TRIPS: BusinessTripRequest[] = [
  {
    id: 'trip-01',
    employee_id: 'emp-06',
    destination_city: 'Surabaya, Jawa Timur',
    purpose: 'On-site technical deployment and client system migration at Pelindo Terminal III.',
    start_date: '2026-10-05',
    end_date: '2026-10-08',
    total_days: 4,
    transportation: 'Flight',
    estimated_cost: 4500000,
    cash_advance_requested: 2500000,
    notes: 'Includes airline tickets Garuda Indo, 3 nights hotel accommodation, and local transport.',
    status: 'PENDING',
    current_approver_id: 'emp-03',
    created_at: '2026-09-29T11:20:00Z',
    employee_name: 'Dewi Lestari',
    employee_code: 'EMP-006',
    department_name: 'Engineering & Technology',
    branch_name: 'Jakarta Head Office',
  },
  {
    id: 'trip-02',
    employee_id: 'emp-16',
    destination_city: 'Balikpapan, Kalimantan Timur',
    purpose: 'Commercial contract negotiation and vendor onboarding with regional oil & gas client.',
    start_date: '2026-09-20',
    end_date: '2026-09-23',
    total_days: 4,
    transportation: 'Flight',
    estimated_cost: 6200000,
    cash_advance_requested: 3000000,
    notes: 'Approved by management. Travel report and SPPD settled.',
    status: 'APPROVED',
    current_approver_id: 'emp-01',
    approver_name: 'Triyanto Andi',
    approver_comment: 'Approved. Please bring back signed MOUs.',
    created_at: '2026-09-15T09:00:00Z',
    employee_name: 'Bambang Irawan',
    employee_code: 'EMP-016',
    department_name: 'Sales & Business Operations',
    branch_name: 'Jakarta Head Office',
  },
];

export const DEMO_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-01',
    user_id: 'emp-06',
    title: 'Leave Request Approved',
    message: 'Your Annual Leave request for Oct 12 - Oct 14 has been approved by Siti Rahmawati.',
    type: 'SUCCESS',
    target_tab: 'leave',
    read: false,
    created_at: '2026-09-30T08:00:00Z',
  },
  {
    id: 'notif-02',
    user_id: 'emp-03',
    title: 'New Overtime Request Pending',
    message: 'Dewi Lestari submitted an Overtime request for 3 hours on project Core Gateway.',
    type: 'ACTION_REQUIRED',
    target_tab: 'approvals-hub',
    read: false,
    created_at: '2026-09-30T08:15:00Z',
  },
  {
    id: 'notif-03',
    user_id: 'emp-03',
    title: 'Business Trip (SPPD) Needs Review',
    message: 'Dewi Lestari requested a 4-day business trip to Surabaya (Pelindo III Deployment).',
    type: 'ACTION_REQUIRED',
    target_tab: 'approvals-hub',
    read: false,
    created_at: '2026-09-30T08:30:00Z',
  },
  {
    id: 'notif-04',
    user_id: 'emp-06',
    title: 'Clock-In Reminder',
    message: 'Regular shift starts at 08:00 WIB. Grace period tolerance is 10 minutes.',
    type: 'INFO',
    target_tab: 'clock-in',
    read: true,
    created_at: '2026-09-30T07:45:00Z',
  },
  {
    id: 'notif-05',
    user_id: 'ALL',
    title: 'Public Holiday Announcement',
    message: 'Upcoming collective leave for Hari Kemerdekaan & Founding Day is scheduled.',
    type: 'INFO',
    target_tab: 'holiday',
    read: true,
    created_at: '2026-09-28T09:00:00Z',
  },
];

export const DEMO_WORK_SCHEDULES: WorkScheduleAssignment[] = [
  {
    id: 'sched-01',
    employee_id: 'emp-06',
    date: '2026-09-30',
    shift_id: 'shift-01',
    is_day_off: false,
    shift_name: 'Regular Office Hours (08:00 - 17:00)',
    start_time: '08:00',
    end_time: '17:00',
    employee_name: 'Dewi Lestari',
  },
  {
    id: 'sched-02',
    employee_id: 'emp-06',
    date: '2026-10-01',
    shift_id: 'shift-01',
    is_day_off: false,
    shift_name: 'Regular Office Hours (08:00 - 17:00)',
    start_time: '08:00',
    end_time: '17:00',
    employee_name: 'Dewi Lestari',
  },
  {
    id: 'sched-03',
    employee_id: 'emp-06',
    date: '2026-10-03',
    shift_id: 'shift-01',
    is_day_off: true,
    shift_name: 'Weekend Off',
    start_time: '-',
    end_time: '-',
    employee_name: 'Dewi Lestari',
  },
  {
    id: 'sched-04',
    employee_id: 'emp-06',
    date: '2026-10-04',
    shift_id: 'shift-01',
    is_day_off: true,
    shift_name: 'Weekend Off',
    start_time: '-',
    end_time: '-',
    employee_name: 'Dewi Lestari',
  },
];

// -------------------------------------------------------------
// PHASE 4 DEMO DATA: SALARY, PAYROLL, CLAIMS, KPI & HUB
// -------------------------------------------------------------

export const DEMO_SALARY_PROFILES: EmployeeSalaryProfile[] = [
  {
    employee_id: 'emp-06', // Dewi Lestari (Senior Frontend)
    base_salary: 16500000,
    position_allowance: 2500000,
    transport_allowance: 1200000,
    meal_allowance: 1100000,
    communication_allowance: 300000,
    bank_name: 'Bank Central Asia (BCA)',
    bank_account_number: '8001239841',
    bank_account_holder: 'Dewi Lestari',
    npwp: '72.910.492.1-013.000',
    bpjs_tk_number: '21098492019',
    bpjs_kes_number: '000192837482',
    ptkp_status: 'TK/0',
  },
  {
    employee_id: 'emp-03', // Budi Santoso (Eng Manager)
    base_salary: 24000000,
    position_allowance: 5000000,
    transport_allowance: 1500000,
    meal_allowance: 1200000,
    communication_allowance: 500000,
    bank_name: 'Bank Mandiri',
    bank_account_number: '1370019284729',
    bank_account_holder: 'Budi Santoso',
    npwp: '54.291.849.2-021.000',
    bpjs_tk_number: '19028374619',
    bpjs_kes_number: '000283749102',
    ptkp_status: 'K/2',
  },
  {
    employee_id: 'emp-02', // Siti Rahmawati (HR Head)
    base_salary: 22000000,
    position_allowance: 4500000,
    transport_allowance: 1500000,
    meal_allowance: 1200000,
    communication_allowance: 500000,
    bank_name: 'Bank Central Asia (BCA)',
    bank_account_number: '6040192847',
    bank_account_holder: 'Siti Rahmawati',
    npwp: '48.102.938.4-019.000',
    bpjs_tk_number: '18029384712',
    bpjs_kes_number: '000382910482',
    ptkp_status: 'K/1',
  },
  {
    employee_id: 'emp-01', // Triyanto Andi (Super Admin / COO)
    base_salary: 35000000,
    position_allowance: 8000000,
    transport_allowance: 2000000,
    meal_allowance: 1500000,
    communication_allowance: 750000,
    bank_name: 'Bank Central Asia (BCA)',
    bank_account_number: '5270192837',
    bank_account_holder: 'Triyanto Andi',
    npwp: '31.928.374.9-011.000',
    bpjs_tk_number: '17019283746',
    bpjs_kes_number: '000102938475',
    ptkp_status: 'K/1',
  },
  {
    employee_id: 'emp-07', // Rizky Pratama (Backend)
    base_salary: 14000000,
    position_allowance: 1500000,
    transport_allowance: 1200000,
    meal_allowance: 1100000,
    communication_allowance: 300000,
    bank_name: 'Bank Negara Indonesia (BNI)',
    bank_account_number: '0382910293',
    bank_account_holder: 'Rizky Pratama',
    npwp: '75.918.273.8-015.000',
    bpjs_tk_number: '21098273619',
    bpjs_kes_number: '000492817264',
    ptkp_status: 'TK/0',
  },
  {
    employee_id: 'emp-08', // Maya Indah (UI/UX)
    base_salary: 13000000,
    position_allowance: 1200000,
    transport_allowance: 1200000,
    meal_allowance: 1100000,
    communication_allowance: 300000,
    bank_name: 'Bank Central Asia (BCA)',
    bank_account_number: '7120938472',
    bank_account_holder: 'Maya Indah',
    npwp: '79.281.938.4-016.000',
    bpjs_tk_number: '21094837261',
    bpjs_kes_number: '000582910283',
    ptkp_status: 'TK/0',
  },
  {
    employee_id: 'emp-10', // Ratna Sari (HR)
    base_salary: 11500000,
    position_allowance: 1000000,
    transport_allowance: 1200000,
    meal_allowance: 1100000,
    communication_allowance: 300000,
    bank_name: 'Bank Mandiri',
    bank_account_number: '1420019283746',
    bank_account_holder: 'Ratna Sari',
    npwp: '81.293.847.1-018.000',
    bpjs_tk_number: '22091827364',
    bpjs_kes_number: '000692817263',
    ptkp_status: 'TK/0',
  },
  {
    employee_id: 'emp-13', // Eko Prasetyo (Finance & Tax)
    base_salary: 13500000,
    position_allowance: 1500000,
    transport_allowance: 1200000,
    meal_allowance: 1100000,
    communication_allowance: 300000,
    bank_name: 'Bank Central Asia (BCA)',
    bank_account_number: '8291029384',
    bank_account_holder: 'Eko Prasetyo',
    npwp: '76.192.837.4-023.000',
    bpjs_tk_number: '20019283746',
    bpjs_kes_number: '000782910283',
    ptkp_status: 'K/1',
  },
];

export const DEMO_PAYROLL_BATCHES: PayrollBatch[] = [
  {
    id: 'batch-2026-09',
    month: 9,
    year: 2026,
    period_label: 'September 2026',
    cut_off_start: '2026-08-26',
    cut_off_end: '2026-09-25',
    payment_date: '2026-09-28',
    total_employees: 8,
    total_gross: 161200000,
    total_deductions: 17482000,
    total_net_payroll: 143718000,
    status: 'PAID',
    notes: 'Payroll rutin bulanan September 2026 telah ditransfer melalui Bank Central Asia (BCA) Corporate Payroll.',
    created_at: '2026-09-25 10:00:00',
    approved_at: '2026-09-27 14:30:00',
    disbursed_at: '2026-09-28 09:15:00',
  },
  {
    id: 'batch-2026-10',
    month: 10,
    year: 2026,
    period_label: 'Oktober 2026',
    cut_off_start: '2026-09-26',
    cut_off_end: '2026-10-25',
    payment_date: '2026-10-28',
    total_employees: 8,
    total_gross: 163850000,
    total_deductions: 17740000,
    total_net_payroll: 146110000,
    status: 'VERIFIED',
    notes: 'Draft payroll periode berjalan Oktober 2026 telah diverifikasi tim People Operations, menunggu Approval Finance.',
    created_at: '2026-09-30 11:30:00',
  },
];

export const DEMO_PAYROLL_ITEMS: PayrollItem[] = [
  // 1. Dewi Lestari (September 2026 - PAID)
  {
    id: 'item-2026-09-emp-06',
    payroll_batch_id: 'batch-2026-09',
    employee_id: 'emp-06',
    employee_code: 'EMP-006',
    employee_name: 'Dewi Lestari',
    department_name: 'Engineering & Technology',
    position_name: 'Senior Frontend Engineer',
    branch_name: 'Jakarta Head Office',
    month: 9,
    year: 2026,
    period_label: 'September 2026',
    work_days: 22,
    present_days: 22,
    late_minutes: 0,
    unpaid_days: 0,
    overtime_hours: 8,

    base_salary: 16500000,
    position_allowance: 2500000,
    transport_allowance: 1200000,
    meal_allowance: 1100000,
    communication_allowance: 300000,
    overtime_pay: 1537572, // ~8 hours at standard formula
    bonus: 0,
    other_earnings: 0,
    gross_income: 23137572,

    late_deduction: 0,
    absence_deduction: 0,
    bpjs_kes_employee: 165000, // 1% capped
    bpjs_tk_jht_employee: 330000, // 2%
    bpjs_tk_jp_employee: 100423, // 1% (capped limit)
    pph21: 1388254, // PPh 21 TER Category A ~6%
    loan_deduction: 0,
    other_deductions: 0,
    total_deductions: 1983677,

    take_home_pay: 21153895,

    bpjs_kes_company: 660000,
    bpjs_tk_jht_company: 610500,
    bpjs_tk_jkk_company: 39600,
    bpjs_tk_jkm_company: 49500,
    bpjs_tk_jp_company: 200846,

    status: 'PAID',
    slip_number: 'SLIP/2026/09/EMP006',
    payment_date: '2026-09-28',
    payment_reference: 'TRX-BCA-20260928-8921',
    bank_name: 'Bank Central Asia (BCA)',
    bank_account_number: '8001239841',
  },

  // 2. Dewi Lestari (Oktober 2026 - VERIFIED)
  {
    id: 'item-2026-10-emp-06',
    payroll_batch_id: 'batch-2026-10',
    employee_id: 'emp-06',
    employee_code: 'EMP-006',
    employee_name: 'Dewi Lestari',
    department_name: 'Engineering & Technology',
    position_name: 'Senior Frontend Engineer',
    branch_name: 'Jakarta Head Office',
    month: 10,
    year: 2026,
    period_label: 'Oktober 2026',
    work_days: 22,
    present_days: 22,
    late_minutes: 15,
    unpaid_days: 0,
    overtime_hours: 4,

    base_salary: 16500000,
    position_allowance: 2500000,
    transport_allowance: 1200000,
    meal_allowance: 1100000,
    communication_allowance: 300000,
    overtime_pay: 768786,
    bonus: 500000,
    other_earnings: 0,
    gross_income: 22868786,

    late_deduction: 50000,
    absence_deduction: 0,
    bpjs_kes_employee: 165000,
    bpjs_tk_jht_employee: 330000,
    bpjs_tk_jp_employee: 100423,
    pph21: 1372127,
    loan_deduction: 0,
    other_deductions: 0,
    total_deductions: 2017550,

    take_home_pay: 20851236,

    bpjs_kes_company: 660000,
    bpjs_tk_jht_company: 610500,
    bpjs_tk_jkk_company: 39600,
    bpjs_tk_jkm_company: 49500,
    bpjs_tk_jp_company: 200846,

    status: 'VERIFIED',
    slip_number: 'SLIP/2026/10/EMP006',
    payment_date: '2026-10-28',
    bank_name: 'Bank Central Asia (BCA)',
    bank_account_number: '8001239841',
  },

  // 3. Budi Santoso (September 2026 - PAID)
  {
    id: 'item-2026-09-emp-03',
    payroll_batch_id: 'batch-2026-09',
    employee_id: 'emp-03',
    employee_code: 'EMP-003',
    employee_name: 'Budi Santoso',
    department_name: 'Engineering & Technology',
    position_name: 'VP of Engineering',
    branch_name: 'Jakarta Head Office',
    month: 9,
    year: 2026,
    period_label: 'September 2026',
    work_days: 22,
    present_days: 22,
    late_minutes: 0,
    unpaid_days: 0,
    overtime_hours: 0,

    base_salary: 24000000,
    position_allowance: 5000000,
    transport_allowance: 1500000,
    meal_allowance: 1200000,
    communication_allowance: 500000,
    overtime_pay: 0,
    bonus: 0,
    other_earnings: 0,
    gross_income: 32200000,

    late_deduction: 0,
    absence_deduction: 0,
    bpjs_kes_employee: 240000,
    bpjs_tk_jht_employee: 480000,
    bpjs_tk_jp_employee: 100423,
    pph21: 2898000,
    loan_deduction: 0,
    other_deductions: 0,
    total_deductions: 3718423,

    take_home_pay: 28481577,

    bpjs_kes_company: 960000,
    bpjs_tk_jht_company: 888000,
    bpjs_tk_jkk_company: 57600,
    bpjs_tk_jkm_company: 72000,
    bpjs_tk_jp_company: 200846,

    status: 'PAID',
    slip_number: 'SLIP/2026/09/EMP003',
    payment_date: '2026-09-28',
    payment_reference: 'TRX-BCA-20260928-8922',
    bank_name: 'Bank Mandiri',
    bank_account_number: '1370019284729',
  },

  // 4. Siti Rahmawati (September 2026 - PAID)
  {
    id: 'item-2026-09-emp-02',
    payroll_batch_id: 'batch-2026-09',
    employee_id: 'emp-02',
    employee_code: 'EMP-002',
    employee_name: 'Siti Rahmawati',
    department_name: 'Human Resources & People',
    position_name: 'Head of People & Operations',
    branch_name: 'Jakarta Head Office',
    month: 9,
    year: 2026,
    period_label: 'September 2026',
    work_days: 22,
    present_days: 22,
    late_minutes: 0,
    unpaid_days: 0,
    overtime_hours: 0,

    base_salary: 22000000,
    position_allowance: 4500000,
    transport_allowance: 1500000,
    meal_allowance: 1200000,
    communication_allowance: 500000,
    overtime_pay: 0,
    bonus: 0,
    other_earnings: 0,
    gross_income: 29700000,

    late_deduction: 0,
    absence_deduction: 0,
    bpjs_kes_employee: 220000,
    bpjs_tk_jht_employee: 440000,
    bpjs_tk_jp_employee: 100423,
    pph21: 2376000,
    loan_deduction: 0,
    other_deductions: 0,
    total_deductions: 3136423,

    take_home_pay: 26563577,

    bpjs_kes_company: 880000,
    bpjs_tk_jht_company: 814000,
    bpjs_tk_jkk_company: 52800,
    bpjs_tk_jkm_company: 66000,
    bpjs_tk_jp_company: 200846,

    status: 'PAID',
    slip_number: 'SLIP/2026/09/EMP002',
    payment_date: '2026-09-28',
    payment_reference: 'TRX-BCA-20260928-8923',
    bank_name: 'Bank Central Asia (BCA)',
    bank_account_number: '6040192847',
  },

  // 5. Triyanto Andi (September 2026 - PAID)
  {
    id: 'item-2026-09-emp-01',
    payroll_batch_id: 'batch-2026-09',
    employee_id: 'emp-01',
    employee_code: 'EMP-001',
    employee_name: 'Triyanto Andi',
    department_name: 'Board of Directors',
    position_name: 'Chief Operating Officer',
    branch_name: 'Jakarta Head Office',
    month: 9,
    year: 2026,
    period_label: 'September 2026',
    work_days: 22,
    present_days: 22,
    late_minutes: 0,
    unpaid_days: 0,
    overtime_hours: 0,

    base_salary: 35000000,
    position_allowance: 8000000,
    transport_allowance: 2000000,
    meal_allowance: 1500000,
    communication_allowance: 750000,
    overtime_pay: 0,
    bonus: 0,
    other_earnings: 0,
    gross_income: 47250000,

    late_deduction: 0,
    absence_deduction: 0,
    bpjs_kes_employee: 350000,
    bpjs_tk_jht_employee: 700000,
    bpjs_tk_jp_employee: 100423,
    pph21: 5670000,
    loan_deduction: 0,
    other_deductions: 0,
    total_deductions: 6820423,

    take_home_pay: 40429577,

    bpjs_kes_company: 1400000,
    bpjs_tk_jht_company: 1295000,
    bpjs_tk_jkk_company: 84000,
    bpjs_tk_jkm_company: 105000,
    bpjs_tk_jp_company: 200846,

    status: 'PAID',
    slip_number: 'SLIP/2026/09/EMP001',
    payment_date: '2026-09-28',
    payment_reference: 'TRX-BCA-20260928-8924',
    bank_name: 'Bank Central Asia (BCA)',
    bank_account_number: '5270192837',
  },
];

export const DEMO_REIMBURSEMENTS: ReimbursementClaim[] = [
  {
    id: 'clm-001',
    employee_id: 'emp-06',
    employee_code: 'EMP-006',
    employee_name: 'Dewi Lestari',
    department_name: 'Engineering & Technology',
    branch_name: 'Jakarta Head Office',
    claim_number: 'CLM-202609-001',
    category: 'BUSINESS_TRIP_SETTLEMENT',
    title: 'Settlement Perjalanan Dinas Surabaya Tech Meetup',
    amount: 1450000,
    date: '2026-09-22',
    description: 'Biaya taksi Bluebird Bandara Juanda ke venue & makan malam bersama tim mitra cabang Surabaya.',
    receipt_url: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=400&q=80',
    status: 'DISBURSED',
    approver_name: 'Budi Santoso',
    approver_notes: 'Pengeluaran sesuai standar plafon SPPD tier 2.',
    approved_at: '2026-09-23 11:20:00',
    disbursed_at: '2026-09-25 15:40:00',
    disbursement_reference: 'DISB-BCA-98129',
    created_at: '2026-09-22 17:30:00',
  },
  {
    id: 'clm-002',
    employee_id: 'emp-06',
    employee_code: 'EMP-006',
    employee_name: 'Dewi Lestari',
    department_name: 'Engineering & Technology',
    branch_name: 'Jakarta Head Office',
    claim_number: 'CLM-202609-002',
    category: 'MEDICAL',
    title: 'Klaim Rawat Jalan & Resep Dokter RS Siloam',
    amount: 875000,
    date: '2026-09-27',
    description: 'Pemeriksaan dokter umum dan obat flu berat (kuitansi asli terlampir).',
    receipt_url: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=400&q=80',
    status: 'APPROVED',
    approver_name: 'Siti Rahmawati',
    approver_notes: 'Plafon rawat jalan tahunan mencukupi (sisa plafon Rp 7.125.000).',
    approved_at: '2026-09-29 09:15:00',
    created_at: '2026-09-28 08:30:00',
  },
  {
    id: 'clm-003',
    employee_id: 'emp-07',
    employee_code: 'EMP-007',
    employee_name: 'Rizky Pratama',
    department_name: 'Engineering & Technology',
    branch_name: 'Jakarta Head Office',
    claim_number: 'CLM-202609-003',
    category: 'TRAINING_CERTIFICATION',
    title: 'Ujian Sertifikasi AWS Certified Solutions Architect',
    amount: 2350000,
    date: '2026-09-26',
    description: 'Biaya registrasi ujian sertifikasi cloud engineering sesuai persetujuan VP Engineering.',
    receipt_url: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=400&q=80',
    status: 'PENDING',
    created_at: '2026-09-28 14:10:00',
  },
  {
    id: 'clm-004',
    employee_id: 'emp-11',
    employee_code: 'EMP-011',
    employee_name: 'Bayu Wicaksono',
    department_name: 'Sales & Business Development',
    branch_name: 'Jakarta Head Office',
    claim_number: 'CLM-202609-004',
    category: 'MEALS_ENTERTAINMENT',
    title: 'Lunch Meeting dengan Klien Enterprise Telkomsel',
    amount: 1120000,
    date: '2026-09-29',
    description: 'Diskusi perpanjangan kontrak tahunan di Plataran Menteng bersama 3 PIC klien.',
    receipt_url: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=400&q=80',
    status: 'PENDING',
    created_at: '2026-09-29 16:45:00',
  },
];

export const DEMO_PERFORMANCES: PerformanceAppraisal[] = [
  {
    id: 'perf-001',
    employee_id: 'emp-06',
    employee_name: 'Dewi Lestari',
    employee_code: 'EMP-006',
    department_name: 'Engineering & Technology',
    position_name: 'Senior Frontend Engineer',
    period: 'Q3 2026',
    year: 2026,
    kpis: [
      {
        id: 'kpi-01',
        title: 'Core App Performance & Core Web Vitals',
        description: 'Mencapai skor Lighthouse > 90 dan LCP < 2.0s di seluruh modul AT-HR.',
        category: 'Quality',
        target: 'Lighthouse > 90',
        weight: 30,
        actual: 'Lighthouse 96, LCP 1.4s',
        score: 95,
      },
      {
        id: 'kpi-02',
        title: 'Delivery Sprint Features On-Time',
        description: 'Menyelesaikan modul Phase 2 & 3 sesuai roadmap tanpa blocking bug.',
        category: 'Core Job',
        target: '100% on schedule',
        weight: 30,
        actual: '100% feature completed with 0 P0 bug',
        score: 98,
      },
      {
        id: 'kpi-03',
        title: 'Disiplin Presensi & Ketepatan Waktu Kerja',
        description: 'Tingkat kehadiran tepat waktu minimal 98% selama periode evaluasi.',
        category: 'Attendance & Discipline',
        target: '≥ 98% On-Time',
        weight: 20,
        actual: '99.2% On-Time, 0 Alpha',
        score: 100,
      },
      {
        id: 'kpi-04',
        title: 'Mentoring Junior & Code Review Velocity',
        description: 'Melakukan review PR maksimal dalam 4 jam kerja dan membimbing 2 intern.',
        category: 'Teamwork',
        target: 'Rata-rata SLA < 4 jam',
        weight: 20,
        actual: 'SLA 2.8 jam, mentoring intern sukses',
        score: 92,
      },
    ],
    final_score: 96.5,
    rating_grade: 'A',
    rating_label: 'Istimewa (Exceeds All Expectations)',
    manager_name: 'Budi Santoso',
    manager_feedback: 'Dewi menunjukkan kepemimpinan teknis luar biasa dalam arsitektur UI dan kedisiplinan kerja yang sangat tinggi. Layak direkomendasikan promosi ke Lead Engineer.',
    self_assessment_notes: 'Berhasil menyelesaikan migrasi modul presensi real-time dan modularisasi komponen tanpa downtime. Ingin mendalami arsitektur micro-frontend di Q4.',
    status: 'FINALIZED',
    reviewed_at: '2026-09-28 16:00:00',
    created_at: '2026-09-20 09:00:00',
  },
  {
    id: 'perf-002',
    employee_id: 'emp-07',
    employee_name: 'Rizky Pratama',
    employee_code: 'EMP-007',
    department_name: 'Engineering & Technology',
    position_name: 'Backend Engineer',
    period: 'Q3 2026',
    year: 2026,
    kpis: [
      {
        id: 'kpi-05',
        title: 'API Response Time & Latency P99',
        description: 'Latency endpoint attendance dan payroll < 120ms.',
        category: 'Quality',
        target: '< 120ms P99',
        weight: 35,
        actual: '88ms P99',
        score: 92,
      },
      {
        id: 'kpi-06',
        title: 'Database Query Optimization & Migration',
        description: 'Implementasi migrasi schema PostgreSQL tanpa lock.',
        category: 'Core Job',
        target: '0 deadlocks',
        weight: 35,
        actual: 'Migrasi lancar, indeks teroptimasi',
        score: 90,
      },
      {
        id: 'kpi-07',
        title: 'Disiplin Presensi & Log Kerja',
        description: 'Kehadiran minimal 95%.',
        category: 'Attendance & Discipline',
        target: '≥ 95% On-Time',
        weight: 30,
        actual: '96.5% On-Time',
        score: 90,
      },
    ],
    final_score: 90.7,
    rating_grade: 'B',
    rating_label: 'Sangat Baik (Meets & Exceeds)',
    manager_name: 'Budi Santoso',
    manager_feedback: 'Performa stabil dan handal dalam penanganan backend. Terus tingkatkan dokumentasi API.',
    self_assessment_notes: 'Berhasil mengoptimalkan indexing table attendance_records sehingga loading report lebih cepat 4x.',
    status: 'FINALIZED',
    reviewed_at: '2026-09-29 11:00:00',
    created_at: '2026-09-20 09:00:00',
  },
];

export const DEMO_ANNOUNCEMENTS: CompanyAnnouncement[] = [
  {
    id: 'anc-001',
    title: 'Surat Edaran Direksi: Kebijakan Libur Bersama Idul Fitri 1447H & Pengaturan Shift Khusus',
    category: 'CIRCULAR_LETTER',
    priority: 'HIGH',
    content: 'Sehubungan dengan Keputusan Bersama 3 Menteri mengenai Hari Libur Nasional dan Cuti Bersama, operasional kantor pusat akan libur mulai tanggal 19 Maret s/d 25 Maret 2026. Tim operasional dan on-call standby diberlakukan skema shift kompensasi lembur 2x tarif Depnaker.',
    published_date: '2026-09-25',
    effective_date: '2026-10-01',
    author_name: 'Siti Rahmawati (Head of People)',
    target_audience: 'ALL',
    attachment_name: 'SE_Direksi_No_042_Libur_Lebaran_2026.pdf',
    pinned: true,
    views_count: 142,
  },
  {
    id: 'anc-002',
    title: 'Sosialisasi Implementasi Sistem Reimbursement Digital & Slip Gaji Paperless di Portal AT-HR',
    category: 'HR_MEMO',
    priority: 'NORMAL',
    content: 'Mulai periode September 2026, seluruh klaim pengeluaran operasional (Reimbursement) dan penerimaan Slip Gaji resmi dapat diakses langsung secara aman melalui portal AT-HR pada menu Finance & Payroll. Karyawan dapat mengunduh bukti potong dan slip gaji dalam format resmi ber-barcode.',
    published_date: '2026-09-28',
    effective_date: '2026-09-28',
    author_name: 'Triyanto Andi (Chief Operating Officer)',
    target_audience: 'ALL',
    attachment_name: 'Panduan_Penggunaan_Payroll_Portal_ATHR.pdf',
    pinned: true,
    views_count: 98,
  },
  {
    id: 'anc-003',
    title: 'Townhall Q3 2026 & All-Hands Meeting: Pencapaian Semester 2 & Apresiasi Tim',
    category: 'EVENT',
    priority: 'NORMAL',
    content: 'Seluruh karyawan diundang menghadiri Townhall Hybrid pada hari Jumat, 3 Oktober 2026 pukul 15.30 WIB di Auditorium Lt. 28 dan via Zoom live streaming. Agenda meliputi update pencapaian revenue, pengumuman Best Employee Q3, dan sesi tanya jawab terbuka bersama Direksi.',
    published_date: '2026-09-29',
    effective_date: '2026-10-03',
    author_name: 'Corporate Communication',
    target_audience: 'ALL',
    attachment_name: 'Townhall_Q3_Agenda.pdf',
    pinned: false,
    views_count: 67,
  },
];

export const DEMO_CONTRACT_TRACKERS: EmployeeContractTracker[] = [
  {
    employee_id: 'emp-17',
    employee_name: 'Kevin Sanjaya',
    employee_code: 'EMP-017',
    department_name: 'Engineering & Technology',
    employment_type: 'Internship',
    contract_start: '2026-04-01',
    contract_end: '2026-10-31',
    days_remaining: 31,
    status: 'EXPIRING_SOON',
    action_needed: 'Evaluasi Konversi ke Junior Engineer PKWT I',
  },
  {
    employee_id: 'emp-18',
    employee_name: 'Anisa Maharani',
    employee_code: 'EMP-018',
    department_name: 'Human Resources & People',
    employment_type: 'Internship',
    contract_start: '2026-05-01',
    contract_end: '2026-11-30',
    days_remaining: 61,
    status: 'ACTIVE',
    action_needed: 'Mid-term Review Magang',
  },
  {
    employee_id: 'emp-11',
    employee_name: 'Bayu Wicaksono',
    employee_code: 'EMP-011',
    department_name: 'Sales & Business Development',
    employment_type: 'Contract',
    contract_start: '2025-11-01',
    contract_end: '2026-10-31',
    days_remaining: 31,
    status: 'EXPIRING_SOON',
    action_needed: 'Perpanjangan Kontrak PKWT II atau Pengangkatan Tetap',
  },
  {
    employee_id: 'emp-12',
    employee_name: 'Nadia Putri',
    employee_code: 'EMP-012',
    department_name: 'Marketing & Growth',
    employment_type: 'Contract',
    contract_start: '2026-01-15',
    contract_end: '2027-01-14',
    days_remaining: 106,
    status: 'ACTIVE',
    action_needed: 'Kontrak aktif berjalan',
  },
];



